### Reading Data From Different Sources

In [39]:
import pandas as pd
from io import StringIO
Data = '{"employee_name": "James", "email": "james@gmail.com", "job_profile": [{"title1":"Team Lead", "title2":"Sr. Developer"}]}'
df=pd.read_json(StringIO(Data))

import requests

url = "https://en.wikipedia.org/wiki/Mobile_country_code"

headers = {"User-Agent": "Mozilla/5.0"}

response = requests.get(url, headers=headers)

df_list = pd.read_html(response.text)

df = df_list[0]  # first table
print(df.head())

   MCC  MNC Brand      Operator       Status Bands (MHz)  \
0    1    1  TEST  Test network  Operational         any
1    1    1  TEST  Test network  Operational         any
2  999   99   NaN  Internal use  Operational         any
3  999  999   NaN  Internal use  Operational         any

                              References and notes
0                                              NaN
1                                              NaN
2  Internal use in private networks, no roaming[6]
3  Internal use in private networks, no roaming[6]

C:\Users\omdha\AppData\Local\Temp\ipykernel_5032\3293054692.py:14: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df_list = pd.read_html(response.text)

In [40]:
df

,MCC,MNC,Brand,Operator,Status,Bands (MHz),References and notes
0,1,1,TEST,Test network,Operational,any,NaN
1,1,1,TEST,Test network,Operational,any,NaN
2,999,99,NaN,Internal use,Operational,any,"Internal use in private networks, no roaming[6]"
3,999,999,NaN,Internal use,Operational,any,"Internal use in private networks, no roaming[6]"

In [41]:
df.to_json()

'{"MCC":{"0":1,"1":1,"2":999,"3":999},"MNC":{"0":1,"1":1,"2":99,"3":999},"Brand":{"0":"TEST","1":"TEST","2":null,"3":null},"Operator":{"0":"Test network","1":"Test network","2":"Internal use","3":"Internal use"},"Status":{"0":"Operational","1":"Operational","2":"Operational","3":"Operational"},"Bands (MHz)":{"0":"any","1":"any","2":"any","3":"any"},"References and notes":{"0":null,"1":null,"2":"Internal use in private networks, no roaming[6]","3":"Internal use in private networks, no roaming[6]"}}'

In [42]:
df.to_json(orient='index')

'{"0":{"MCC":1,"MNC":1,"Brand":"TEST","Operator":"Test network","Status":"Operational","Bands (MHz)":"any","References and notes":null},"1":{"MCC":1,"MNC":1,"Brand":"TEST","Operator":"Test network","Status":"Operational","Bands (MHz)":"any","References and notes":null},"2":{"MCC":999,"MNC":99,"Brand":null,"Operator":"Internal use","Status":"Operational","Bands (MHz)":"any","References and notes":"Internal use in private networks, no roaming[6]"},"3":{"MCC":999,"MNC":999,"Brand":null,"Operator":"Internal use","Status":"Operational","Bands (MHz)":"any","References and notes":"Internal use in private networks, no roaming[6]"}}'

In [43]:
df.to_json(orient='records')

'[{"MCC":1,"MNC":1,"Brand":"TEST","Operator":"Test network","Status":"Operational","Bands (MHz)":"any","References and notes":null},{"MCC":1,"MNC":1,"Brand":"TEST","Operator":"Test network","Status":"Operational","Bands (MHz)":"any","References and notes":null},{"MCC":999,"MNC":99,"Brand":null,"Operator":"Internal use","Status":"Operational","Bands (MHz)":"any","References and notes":"Internal use in private networks, no roaming[6]"},{"MCC":999,"MNC":999,"Brand":null,"Operator":"Internal use","Status":"Operational","Bands (MHz)":"any","References and notes":"Internal use in private networks, no roaming[6]"}]'

In [44]:
df = pd.read_csv('wine.data')

In [45]:
df.head()

,1,14.23,1.71,2.43,15.6,127,2.8,3.06,.28,2.29,5.64,1.04,3.92,1065
0,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
1,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
2,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
3,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735
4,1,14.20,1.76,2.45,15.2,112,3.27,3.39,0.34,1.97,6.75,1.05,2.85,1450

In [46]:
df.to_csv("wine.csv")

In [47]:
!pip install lxml

Requirement already satisfied: lxml in c:\users\omdha\anaconda3\lib\site-packages (5.3.0)

In [48]:
!pip install html5lib
!pip install beautifulsoup4

Requirement already satisfied: html5lib in c:\users\omdha\anaconda3\lib\site-packages (1.1)
Requirement already satisfied: six>=1.9 in c:\users\omdha\anaconda3\lib\site-packages (from html5lib) (1.17.0)
Requirement already satisfied: webencodings in c:\users\omdha\anaconda3\lib\site-packages (from html5lib) (0.5.1)
Requirement already satisfied: beautifulsoup4 in c:\users\omdha\anaconda3\lib\site-packages (4.13.5)
Requirement already satisfied: soupsieve>1.2 in c:\users\omdha\anaconda3\lib\site-packages (from beautifulsoup4) (2.5)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\omdha\anaconda3\lib\site-packages (from beautifulsoup4) (4.15.0)

In [49]:
url="https://www.fdic.gov/resources/resolutions/bank-failures/failed-bank-list/"

df=pd.read_html(url)

In [50]:
df[0]

,Bank Name,City,State,Cert,Acquiring Institution,Closing Date,Fund Sort ascending
0,Metropolitan Capital Bank & Trust,Chicago,Illinois,57488,First Independence Bank,"January 30, 2026",10550
1,The Santa Anna National Bank,Santa Anna,Texas,5520,Coleman County State Bank,"June 27, 2025",10549
2,Pulaski Savings Bank,Chicago,Illinois,28611,Millennium Bank,"January 17, 2025",10548
3,The First National Bank of Lindsay,Lindsay,Oklahoma,4134,First Bank & Trust Co.,"October 18, 2024",10547
4,Republic First Bank dba Republic Bank,Philadelphia,Pennsylvania,27332,"Fulton Bank, National Association","April 26, 2024",10546
5,Citizens Bank,Sac City,Iowa,8758,Iowa Trust & Savings Bank,"November 3, 2023",10545
6,Heartland Tri-State Bank,Elkhart,Kansas,25851,"Dream First Bank, N.A.","July 28, 2023",10544
7,First Republic Bank,San Francisco,California,59017,"JPMorgan Chase Bank, N.A.","May 1, 2023",10543
8,Signature Bank,New York,New York,57053,"Flagstar Bank, N.A.","March 12, 2023",10540
9,Silicon Valley Bank,Santa Clara,California,24735,First–Citizens Bank & Trust Company,"March 10, 2023",10539
10,Almena State Bank,Almena,Kansas,15426,Equity Bank,"October 23, 2020",10538
11,First City Bank of Florida,Fort Walton Beach,Florida,16748,"United Fidelity Bank, fsb","October 16, 2020",10537
12,The First State Bank,Barboursville,West Virginia,14361,"MVB Bank, Inc.","April 3, 2020",10536
13,Ericson State Bank,Ericson,Nebraska,18265,Farmers and Merchants Bank,"February 14, 2020",10535
14,City National Bank of New Jersey,Newark,New Jersey,21111,Industrial Bank,"November 1, 2019",10534
15,Resolute Bank,Maumee,Ohio,58317,Buckeye State Bank,"October 25, 2019",10533
16,Louisa Community Bank,Louisa,Kentucky,58112,Kentucky Farmers Bank Corporation,"October 25, 2019",10532
17,The Enloe State Bank,Cooper,Texas,10716,"Legend Bank, N. A.","May 31, 2019",10531
18,Washington Federal Bank for Savings,Chicago,Illinois,30570,Royal Savings Bank,"December 15, 2017",10530
19,The Farmers and Merchants State Bank of Argonia,Argonia,Kansas,17719,Conway Bank,"October 13, 2017",10529
20,Fayette County Bank,Saint Elmo,Illinois,1802,"United Fidelity Bank, fsb","May 26, 2017",10528
21,"Guaranty Bank, (d/b/a BestBank in Georgia & Mi...",Milwaukee,Wisconsin,30003,First-Citizens Bank & Trust Company,"May 5, 2017",10527
22,First NBC Bank,New Orleans,Louisiana,58302,Whitney Bank,"April 28, 2017",10526
23,Proficio Bank,Cottonwood Heights,Utah,35495,Cache Valley Bank,"March 3, 2017",10525
24,Seaway Bank and Trust Company,Chicago,Illinois,19328,State Bank of Texas,"January 27, 2017",10524

In [57]:
url = "https://en.wikipedia.org/wiki/Mobile_country_code"

pd.read_html(response.text,match="Country",header=0)[0]

C:\Users\omdha\AppData\Local\Temp\ipykernel_5032\1211146801.py:3: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  pd.read_html(response.text,match="Country",header=0)[0]

,Mobile country code,Country,ISO 3166,Mobile network codes,National MNC authority,Remarks
0,289,A Abkhazia,GE-AB,List of mobile network codes in Abkhazia,NaN,MCC is not listed by ITU
1,412,Afghanistan,AF,List of mobile network codes in Afghanistan,NaN,NaN
2,276,Albania,AL,List of mobile network codes in Albania,NaN,NaN
3,603,Algeria,DZ,List of mobile network codes in Algeria,NaN,NaN
4,544,American Samoa (United States of America),AS,List of mobile network codes in American Samoa,NaN,NaN
...,...,...,...,...,...,...
247,452,Vietnam,VN,List of mobile network codes in the Vietnam,NaN,NaN
248,543,W Wallis and Futuna,WF,List of mobile network codes in Wallis and Futuna,NaN,NaN
249,421,Y Yemen,YE,List of mobile network codes in the Yemen,NaN,NaN
250,645,Z Zambia,ZM,List of mobile network codes in Zambia,NaN,NaN
251,648,Zimbabwe,ZW,List of mobile network codes in Zimbabwe,NaN,NaN

In [60]:
!pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\omdha\anaconda3\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\omdha\anaconda3\lib\site-packages (from openpyxl) (2.0.0)

In [62]:
df_excel=pd.read_excel('Book1.xlsx')

In [63]:
df_excel.to_pickle('df_excel')

In [64]:
pd.read_pickle('df_excel')

    Name  Age
0     OM   19
1  Dhruv   18
2    Ram   20